import "@/styles/globals.scss";
import type { Metadata } from "next";
import localFont from 'next/font/local';

const helvetica = localFont({
  src: [
    {
      path: '../../public/assets/fonts/helvetica.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/helvetica-bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/assets/fonts/helvetica-light.ttf',
      weight: '300',
      style: 'light',
    }
  ],
  variable: '--font-helvetica',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
